spring.application.name=backend

server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT Security
app.security.jwt.secret=${JWT_SECRET}
app.security.jwt.access-token-ttl=PT1H
app.security.jwt.refresh-token-ttl=P7D
